[package]
name = "cargo-smol"
version = "0.1.0"
authors = ["rhay <me@russellhay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
term = "0.6.1"
termion = "1.5.3"
